Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
